WolfDen/Models/SaveAndLoad/Save.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WolfDen.Models.SaveAndLoad
{
    public class Save
    {
        public int SaveId { get; set; }
        public string Name { get; set; }
        public byte[] CompressedMoves { get; set; }
        public List<SavedAdvanceWarsPlayer> Players { get; set; } = new List<SavedAdvanceWarsPlayer>();
        public int MapId { get; set; }
        public int Seed { get; set; }

    }
}

WolfDen/Pages/Saving/Load.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WolfDen.Data;
using WolfDen.Models;
using WolfDen.Models.SaveAndLoad;
using WolfDen.Services;

namespace WolfDen.Pages
{
    [Authorize]
    public class LoadModel : PageModel
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly LoadService loadService;
        private readonly ISavingService savingService;
        public List<Save> Saves;

        public LoadModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager, LoadService loadService, ISavingService savingService)
        {
            this.context = context;
            this.userManager = userManager;
            this.loadService = loadService;
            this.savingService = savingService;
        }

        public async Task OnGetAsync()
        {
            Saves = await GetSaves();
        }

        public async Task<ActionResult> OnPostLoad()
        {
            Saves = await GetSaves();
            int saveId;
            if (!int.TryParse(Request.Form["saveId"][0], out saveId))
                return Page();
            var save = Saves.Where(s => s.SaveId == saveId).FirstOrDefault();
            if (save == null)
                return Page();

            var gameId = await loadService.Load(save);

            return RedirectToPage("/Game/Game", new { id = gameId });
        }

        public async Task<ActionResult> OnPostReplay()
        {
            Saves = await GetSaves();
            int saveId;
            if (!int.TryParse(Request.Form["saveId"][0], out saveId))
                return Page();
            var save = Saves.Where(s => s.SaveId == saveId).FirstOrDefault();
            if (save == null)
                return Page();

            var gameId = await loadService.LoadReplay(save);

            return RedirectToPage("/Game/Game", new { id = gameId });
        }

        public async Task<ActionResult> OnPostDelete()
        {
            int saveId;
            if (int.TryParse(Request.Form["saveId"][0], out saveId))
            {
                var user = await userManager.GetUserAsync(User);
                await savingService.DeleteSave(user.Id, saveId);
            }

            Saves = await GetSaves();
            return Page();
        }

        private async Task<List<Save>> GetSaves()
        {
            var user = await userManager.GetUserAsync(User);
            var userWithSaves = await context.Users.Where(u => u.Id == user.Id).Include(u => u.Saves).ThenInclude(s => s.Players).FirstOrDefaultAsync();
            return userWithSaves.Saves;
        }
    }
}

WolfDen/Pages/Saving/Save.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WolfDen.Data;
using Microsoft.EntityFrameworkCore;
using WolfDen.Models;
using WolfDen.Models.SaveAndLoad;
using WolfDen.Services;
using WolfDen.Hubs;
using WolfDen.Game;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Configuration;

namespace WolfDen.Pages
{
    public class SaveModel : PageModel
    {
        private const byte maxNumberOfSaves = 13;
        public class SavePost
        {
            public string Id { get; set; }
            [Required]
            public string Name { get; set; }
        }

        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext context;
        private readonly ISavingService savingService;
        private readonly IConfiguration configuration;

        public List<Save> Saves { get; set; }
        public string Id { get; set; }

        public SaveModel(UserManager<ApplicationUser> userManager, ApplicationDbContext context, ISavingService savingService, IConfiguration configuration)
        {
            this.userManager = userManager;
            this.context = context;
            this.savingService = savingService;
            this.configuration = configuration;
        }

        public async Task<ActionResult> OnGetAsync(string id)
        {          
            Id = id;

            var user = await userManager.GetUserAsync(User);
            var userWithSaves = await context.Users.Where(u => u.Id == user.Id).Include(u => u.Saves).ThenInclude(s => s.Players).FirstOrDefaultAsync();
            Saves = userWithSaves.Saves;

            return Page();
        }
        
        [BindProperty]
        public SavePost Post { get; set; }

        public async Task<ActionResult> OnPostAsync(string id)
        {
            var user = await userManager.GetUserAsync(User);
            var userWithSaves = await context.Users.Where(u => u.Id == user.Id).Include(u => u.Saves).ThenInclude(s => s.Players).FirstOrDefaultAsync();
            Saves = userWithSaves.Saves;

            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Don't allow to many saves
            var adminUserId = configuration.GetValue<string>("AdminUserId");
            if (user.Id != adminUserId && Saves.Count >= maxNumberOfSaves && Saves.Where(s => s.Name == Post.Name).Count() == 0)
            {
                ModelState.AddModelError(string.Empty, "Maximum number of saves reached.");
                return Page();
            }

            Id = id;
            Guid gameId;
            if (!Guid.TryParse(id, out gameId))
                return RedirectToPage("./SaveFailed");

            Save save = null;
            GameHub.GameOperation(gameId, (WolfDen.Game.Game game) => {
                save = savingService.GetSave(Post.Name, game as AdvanceWarsGame);
            });

            if (save == null)
                return RedirectToPage("./SaveFailed");

            await savingService.Save(user.Id, save);

            return RedirectToPage("./SaveSuccesfull");
        }
    }
}

WolfDen/Pages/Saving/Load.cshtml
@page
@model WolfDen.Pages.LoadModel
@{
    ViewData["Title"] = "Load";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Load</h1>
<div class="row">
    <div class="col-12">


        <table class="table table-hover">
            <tbody>
                @foreach (var save in Model.Saves)
                {
                <tr>
                    <td>@save.Name</td>

                    <td style="width:80px;">
                        <form asp-page-handler="load" method="post">
                            <button class="btn btn-primary" type="submit" name="saveId" value="@save.SaveId">Load</button>
                        </form>
                    </td>
                    <td style="width:80px;">
                        <form asp-page-handler="replay" method="post">
                            <button class="btn btn-secondary" type="submit" name="saveId" value="@save.SaveId">Replay</button>
                        </form>
                    </td>
                    <td style="width:80px;">
                        <form asp-page-handler="delete" method="post">
                            <button class="btn btn-danger" type="submit" name="saveId" value="@save.SaveId">Delete</button>
                        </form>
                    </td>

                </tr>

                }
            </tbody>
        </table>
    </div>
</div>

WolfDen/Pages/Saving/Save.cshtml
@page
@model WolfDen.Pages.SaveModel
@{
    ViewData["Title"] = "Save";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col">

        <h1 id="save">Save</h1>

        <select class="form-control" size="13" id="saves" style="width:100%;">
            @foreach (var save in Model.Saves)
            {
                <option value="@save.Name">@save.Name</option>
            }
        </select><br />

        @using (Html.BeginForm())
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" value="@Model.Id" asp-for="Post.Id" />
            <div class="form-group">
                <label for="Name">Name</label>
                <input id="nameInput" class="form-control" placeholder="Example game name" asp-for="Post.Name" />
                <input type="submit" value="Submit" class="btn btn-primary btn-lg btn-block" />
                <span asp-validation-for="Post.Name" class="text-danger"></span>
            </div>
        }
    </div>
</div>

WolfDen/Pages/Saving/SaveFailed.cshtml
@page
@{
    ViewData["Title"] = "SaveFailed";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}



<div class="row Index">
    <div class="col-md-4" style="text-align:center;">
        <img height="600" src="~/Images/art/aw2-adder.png" />
    </div>
    <div class="col-md-6 Message">
        <div id="speechBox" class="bg-white">
            <img id="speechBoxImg" src="~/Images/art/speechBox.png" />
            <h2 class="">It would appear something went wrong with your save. What a shame.</h2>
        </div>
    </div>
</div>

WolfDen/Pages/Saving/SaveSuccesfull.cshtml
@page
@{
    ViewData["Title"] = "SaveSuccesfull";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="row Index">
    <div class="col-md-4" style="text-align:center;">
        <img height="600" src="~/Images/art/aw2-andy.png" />
    </div>
    <div class="col-md-6 Message">
        <div id="speechBox" class="bg-white">
            <img id="speechBoxImg" src="~/Images/art/speechBox.png" />
            <h2 class="">Game saved!</h2>
        </div>
    </div>
</div>